# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = "20a3b514-e960-49b5-bdb3-5b784ef2bf26"
  config.password       = "dspassword"
  config.integrator_key = "d9f40d5a-2806-40d1-8fae-9ff58de023d6"
  config.account_id     = "65bef886-5851-48e3-97ec-06f9f7a454d1"
  config.endpoint       = "https://demo.docusign.net/restapi/"
  config.api_version    = "v2"
end

